language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.14.0
cache: cargo

script:
  - cargo build --verbose --features=fuzztarget
  - cargo build --verbose --features=rand
  - cargo test --verbose --features=rand
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release
  - cargo test --release
  - cargo bench
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cargo doc; fi
